'use strict';
// Contact-form core: validation, sanitisation, abuse controls and email delivery.
// Pure functions + small in-memory stores so it can be unit-tested without a server.
// Files in /api prefixed with "_" are helpers, not deployed as endpoints.

const DEFAULT_TO = 'afradigital.hello@gmail.com';
// Sender must be on the domain verified in Resend. Resend's shared test sender (onboarding@resend.dev)
// can only deliver to the Resend account owner's own address, so it is never used here.
const DEFAULT_SENDER_DOMAIN = 'afra-digital.com';
const DEFAULT_FROM = 'AFRA DIGITAL Website <website@afra-digital.com>';
const DEFAULT_API_URL = 'https://api.resend.com/emails';

// Must match the <option> values in the contact form.
const SERVICES = Object.freeze([
  'AI Solutions',
  'Business Automation',
  'Website Development',
  'Web Applications',
  'Custom Software',
  'SaaS Development',
  'Mobile App Development',
  'UI/UX Design',
  'Branding',
  'E-Commerce Development',
  'Digital Marketing',
  'Digital Transformation',
  'Cook With Fire (Restaurant Platform)',
  'SAANIX (Business Platform)',
  'Other / Not Sure',
]);

// Phase 04 optional qualification fields — values must match the <option> values exactly.
const BUDGETS = Object.freeze(['Under QAR 10,000', 'QAR 10,000–25,000', 'QAR 25,000–50,000', 'Over QAR 50,000', 'Not sure yet']);
const TIMELINES = Object.freeze(['As soon as possible', 'Within 1–3 months', 'Within 3–6 months', 'Just exploring']);
const CONTACT_PREFS = Object.freeze(['Email', 'WhatsApp', 'Phone']);
const PLANS = Object.freeze(['Starter', 'Business', 'Enterprise']);
const SOURCE_RE = /^[a-z0-9_]{1,40}$/; // CTA used to reach the form (e.g. "pricing_business"); page-generated, not user text

const LIMITS = Object.freeze({ firstName: 80, lastName: 80, email: 254, phone: 30, company: 120, message: 5000 });
const MAX_BODY_BYTES = 20 * 1024;
const MIN_FILL_MS = 2500;

const CONTROL_SINGLE = new RegExp("[\u0000-\u001F\u007F-\u009F\u2028\u2029]", "g"); // includes CR/LF/TAB and Unicode line separators
const CONTROL_MULTI = /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F-\u009F]/g; // keeps \n and \t
const EMAIL_RE = /^[^\s@<>()[\]\\,;:"]+@[^\s@<>()[\]\\,;:"]+\.[^\s@<>()[\]\\,;:"]{2,}$/;
const PHONE_RE = /^\+?[0-9 ().-]{6,30}$/;

/** Normalise a submitted value. Returns '' for missing, null for non-string (invalid). */
function cleanText(value, { multiline = false } = {}) {
  if (value === undefined || value === null) return '';
  if (typeof value !== 'string') return null;
  let v = value.normalize('NFC');
  if (multiline) v = v.replace(/\r\n?/g, '\n').replace(CONTROL_MULTI, '');
  else v = v.replace(CONTROL_SINGLE, ' ').replace(/\s+/g, ' ');
  return v.trim();
}

/**
 * Validate and sanitise a raw submission.
 * @returns {{ ok: true, data: object } | { ok: false, fields: Record<string,string> }}
 * Field error codes: required | too_long | invalid
 */
function validateSubmission(raw) {
  const fields = {};
  const src = raw && typeof raw === 'object' ? raw : {};
  const data = {
    firstName: cleanText(src.firstName),
    lastName: cleanText(src.lastName),
    email: cleanText(src.email),
    phone: cleanText(src.phone),
    company: cleanText(src.company),
    service: cleanText(src.service),
    message: cleanText(src.message, { multiline: true }),
    budget: cleanText(src.budget),
    timeline: cleanText(src.timeline),
    contactPref: cleanText(src.contactPref),
    plan: cleanText(src.plan),
  };
  // The source CTA is generated by the page, not typed by the visitor: unexpected values are dropped, not errors.
  const source = cleanText(src.source);
  data.source = source && SOURCE_RE.test(source) ? source : '';
  for (const [k, v] of Object.entries(data)) if (v === null) { fields[k] = 'invalid'; data[k] = ''; }

  for (const k of ['firstName', 'lastName']) {
    if (fields[k]) continue;
    if (!data[k]) fields[k] = 'required';
    else if (data[k].length > LIMITS[k]) fields[k] = 'too_long';
    else if (!/\p{L}/u.test(data[k])) fields[k] = 'invalid';
  }
  if (!fields.email) {
    if (!data.email) fields.email = 'required';
    else if (data.email.length > LIMITS.email) fields.email = 'too_long';
    else if (!EMAIL_RE.test(data.email) || data.email.split('@')[0].length > 64) fields.email = 'invalid';
    else data.email = data.email.toLowerCase();
  }
  if (!fields.phone && data.phone) {
    const digits = data.phone.replace(/\D/g, '').length;
    if (data.phone.length > LIMITS.phone) fields.phone = 'too_long';
    else if (!PHONE_RE.test(data.phone) || digits < 6 || digits > 15) fields.phone = 'invalid';
  }
  if (!fields.company && data.company.length > LIMITS.company) fields.company = 'too_long';
  if (!fields.service && data.service && !SERVICES.includes(data.service)) fields.service = 'invalid';
  if (!fields.message && data.message.length > LIMITS.message) fields.message = 'too_long';
  if (!fields.budget && data.budget && !BUDGETS.includes(data.budget)) fields.budget = 'invalid';
  if (!fields.timeline && data.timeline && !TIMELINES.includes(data.timeline)) fields.timeline = 'invalid';
  if (!fields.contactPref && data.contactPref && !CONTACT_PREFS.includes(data.contactPref)) fields.contactPref = 'invalid';
  if (!fields.plan && data.plan && !PLANS.includes(data.plan)) fields.plan = 'invalid';
  // Asking to be contacted by WhatsApp or phone needs a number to contact.
  if (!fields.contactPref && !fields.phone && (data.contactPref === 'WhatsApp' || data.contactPref === 'Phone') && !data.phone) {
    fields.phone = 'required_for_contact';
  }

  return Object.keys(fields).length ? { ok: false, fields } : { ok: true, data };
}

/** Bot heuristics. Returns null if OK, otherwise a reason code. */
function checkBotSignals(raw) {
  const src = raw && typeof raw === 'object' ? raw : {};
  if (typeof src.hp === 'string' && src.hp.trim() !== '') return 'rejected';
  if (src.hp !== undefined && typeof src.hp !== 'string') return 'rejected';
  // `elapsed` is filled by the page script (ms since the form was shown). Missing = no-JS submission.
  if (src.elapsed !== undefined && src.elapsed !== '') {
    const n = Number(src.elapsed);
    if (!Number.isFinite(n) || n < MIN_FILL_MS) return 'too_fast';
  }
  return null;
}

/** Sliding-window rate limiter (per serverless instance — best effort, see report). */
function createRateLimiter({ limit, windowMs, now = () => Date.now() }) {
  const hits = new Map();
  return {
    check(key) {
      const t = now();
      const arr = (hits.get(key) || []).filter(x => t - x < windowMs);
      if (arr.length >= limit) {
        hits.set(key, arr);
        return { allowed: false, retryAfterSec: Math.max(1, Math.ceil((windowMs - (t - arr[0])) / 1000)) };
      }
      arr.push(t); hits.set(key, arr);
      if (hits.size > 5000) for (const [k, v] of hits) if (!v.length || t - v[v.length - 1] > windowMs) hits.delete(k);
      return { allowed: true, retryAfterSec: 0 };
    },
  };
}

/** Remembers recently delivered submissions so a double-submit doesn't send twice (and keeps its reference). */
function createDuplicateGuard({ windowMs, now = () => Date.now() }) {
  const seen = new Map();
  const key = d => [d.email, d.firstName, d.lastName, d.service, d.message].join('\u0001');
  const live = d => { const e = seen.get(key(d)); return e && now() - e.t < windowMs ? e : null; };
  return {
    isDuplicate(d) { return !!live(d); },
    referenceFor(d) { const e = live(d); return e ? e.ref : null; },
    remember(d, ref) {
      const t = now(); seen.set(key(d), { t, ref: ref || null });
      if (seen.size > 2000) for (const [k, v] of seen) if (t - v.t > windowMs) seen.delete(k);
    },
  };
}

// Enquiry reference: random (crypto), non-sequential, contains no personal data, no ambiguous characters.
const REF_ALPHABET = '23456789ABCDEFGHJKLMNPQRSTUVWXYZ';
const REFERENCE_RE = /^AFRA-[2-9A-HJ-NP-Z]{6}$/;
function makeReference() {
  const crypto = require('node:crypto');
  let out = '';
  for (let i = 0; i < 6; i++) out += REF_ALPHABET[crypto.randomInt(REF_ALPHABET.length)];
  return 'AFRA-' + out;
}

function singleLine(s, max) {
  const v = String(s).replace(CONTROL_SINGLE, ' ').replace(/\s+/g, ' ').trim();
  return v.length > max ? v.slice(0, max - 1) + '…' : v;
}

/** Build a plain-text email (no HTML => no HTML injection in the inbox). */
function composeEmail(data, { submittedAt = new Date(), reference = '' } = {}) {
  const name = `${data.firstName} ${data.lastName}`.trim();
  const ref = REFERENCE_RE.test(reference) ? reference : '';
  const subject = singleLine(`Website enquiry${ref ? ' [' + ref + ']' : ''}: ${data.service || 'General'} — ${name}`, 150);
  const lines = [
    'New enquiry from the AFRA DIGITAL website contact form.',
    '',
    `Name:     ${name}`,
    `Email:    ${data.email}`,
    `Phone:    ${data.phone || '—'}`,
    `Company:  ${data.company || '—'}`,
    `Service:  ${data.service || '—'}`,
    `Package:  ${data.plan || '—'}`,
    `Budget:   ${data.budget || '—'}`,
    `Timeline: ${data.timeline || '—'}`,
    `Preferred contact: ${data.contactPref || '—'}`,
    '',
    'Project brief:',
    data.message || '—',
    '',
    '---',
    ...(ref ? [`Reference: ${ref}`] : []),
    `Submitted: ${submittedAt.toISOString()} (UTC)`,
    `Source:    ${data.source ? 'website button "' + data.source + '"' : 'direct'}`,
    'Reply to this email to respond directly to the enquirer.',
  ];
  return { subject, text: lines.join('\n') };
}

/**
 * Delivery failure. `kind` is a stable diagnostic code (safe to log, never shown verbatim to visitors):
 *   auth                     – API key missing/invalid/restricted (401/403)
 *   test_sender_restriction  – resend.dev test sender used for a non-owner recipient (403)
 *   sender_unverified        – from-address domain not verified in Resend (403/422)
 *   recipient_rejected       – recipient not allowed by the account (403/422)
 *   validation               – provider rejected the payload (400/422)
 *   provider_rate_limited    – provider 429
 *   rejected                 – other 4xx
 *   provider_unavailable     – provider 5xx
 *   network                  – could not reach provider
 *   timeout                  – no response within the time limit (delivery state unknown)
 */
class DeliveryError extends Error {
  constructor(kind, status, detail) { super(`delivery ${kind}`); this.kind = kind; this.status = status; this.detail = detail || ''; }
}

const EMAIL_IN_TEXT = /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g;
/** Strip email addresses and control characters, cap length — provider messages can echo account emails. */
function sanitizeForLog(s, max = 200) {
  return String(s || '').replace(EMAIL_IN_TEXT, '[email]').replace(/[\u0000-\u001F\u007F]+/g, ' ').slice(0, max);
}

/** Map a Resend error response to a diagnostic kind. */
function classifyProviderError(status, body) {
  const name = String((body && body.name) || '').toLowerCase();
  const msg = String((body && body.message) || '').toLowerCase();
  if (status === 401 || /api[_ ]?key/.test(name) || /api key is invalid|invalid api key|missing api key|restricted/.test(msg)) return 'auth';
  if (/resend\.dev|testing emails|for testing/.test(msg)) return 'test_sender_restriction';
  if (/domain.*not verified|verify a domain|not verified|invalid_from_address|from.*address/.test(msg + ' ' + name)) return 'sender_unverified';
  if (/recipient|not allowed to send|to.*not allowed/.test(msg)) return 'recipient_rejected';
  if (status === 429) return 'provider_rate_limited';
  if (status >= 500) return 'provider_unavailable';
  if (status === 400 || status === 422 || name === 'validation_error') return 'validation';
  return 'rejected';
}

/** Parse "Display Name <addr@domain>" or "addr@domain"; returns the bare address or null. */
function addressOf(from) {
  const m = String(from || '').match(/<([^<>\s]+)>\s*$/);
  const addr = (m ? m[1] : String(from || '')).trim();
  return /^[^\s@<>()[\]\\,;:"]+@[^\s@<>()[\]\\,;:"]+\.[A-Za-z]{2,}$/.test(addr) ? addr.toLowerCase() : null;
}

/**
 * Read and validate provider configuration from the environment (server-side only).
 * `problem` is set when delivery must not be attempted. Secret values are never logged or returned to clients.
 */
function getConfig(env = process.env) {
  const apiKey = String(env.RESEND_API_KEY || '').trim();
  const senderDomain = String(env.CONTACT_SENDER_DOMAIN || DEFAULT_SENDER_DOMAIN).trim().toLowerCase();
  const from = String(env.CONTACT_FROM_EMAIL || DEFAULT_FROM).trim();
  const to = String(env.CONTACT_TO_EMAIL || DEFAULT_TO).trim();
  const fromAddr = addressOf(from);
  const fromDomain = fromAddr ? fromAddr.split('@')[1] : '';

  let problem = null;
  if (!apiKey) problem = 'missing_api_key';
  else if (/[\r\n]/.test(from) || !fromAddr) problem = 'invalid_from';
  else if (fromDomain === 'resend.dev' || fromDomain.endsWith('.resend.dev')) problem = 'test_sender_not_allowed';
  else if (fromDomain !== senderDomain && !fromDomain.endsWith('.' + senderDomain)) problem = 'sender_domain_mismatch';
  else if (!addressOf(to) || /[\r\n,;]/.test(to)) problem = 'invalid_to';

  return {
    configured: problem === null,
    problem,
    apiKey,
    apiUrl: String(env.RESEND_API_URL || DEFAULT_API_URL).trim(),
    to,
    from,
    fromDomain,
    senderDomain,
    allowedOrigins: String(env.CONTACT_ALLOWED_ORIGINS || 'https://www.afra-digital.com,https://afra-digital.com')
      .split(',').map(s => s.trim()).filter(Boolean),
  };
}

/** Stable key per submission so a retry (or provider-side dedupe) never produces two notifications. */
function idempotencyKey(data) {
  const crypto = require('node:crypto');
  return 'afra-contact-' + crypto.createHash('sha256')
    .update([data.email, data.firstName, data.lastName, data.service, data.message].join('\u0001'))
    .digest('hex').slice(0, 40);
}

async function attempt(config, payload, key, { fetchImpl, timeoutMs }) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  let res;
  try {
    res = await fetchImpl(config.apiUrl, {
      method: 'POST',
      headers: { Authorization: `Bearer ${config.apiKey}`, 'Content-Type': 'application/json', 'Idempotency-Key': key },
      body: payload,
      signal: controller.signal,
    });
  } catch (err) {
    throw new DeliveryError(err && err.name === 'AbortError' ? 'timeout' : 'network');
  } finally {
    clearTimeout(timer);
  }
  let body = null;
  try { body = await res.json(); } catch { /* non-JSON body */ }
  if (res.status >= 200 && res.status < 300) return { id: (body && body.id) || null };
  const kind = classifyProviderError(res.status, body);
  const detail = body ? `${sanitizeForLog(body.name, 40)}: ${sanitizeForLog(body.message)}` : '';
  throw new DeliveryError(kind, res.status, detail);
}

/**
 * Send via the Resend HTTP API (no SDK). Resolves only when Resend accepts the email (2xx).
 * Permanent rejections (4xx) are never retried; one retry for network errors / 5xx, same idempotency key.
 */
async function deliver(config, data, { fetchImpl = fetch, timeoutMs = 7000, retryDelayMs = 400, submittedAt, reference } = {}) {
  const { subject, text } = composeEmail(data, { submittedAt, reference });
  const payload = JSON.stringify({ from: config.from, to: [config.to], reply_to: data.email, subject, text });
  const key = idempotencyKey(data);
  try {
    return await attempt(config, payload, key, { fetchImpl, timeoutMs });
  } catch (err) {
    if (err.kind !== 'network' && err.kind !== 'provider_unavailable') throw err;
    await new Promise(r => setTimeout(r, retryDelayMs));
    return attempt(config, payload, key, { fetchImpl, timeoutMs });
  }
}

/** Same-origin or allow-listed Origin. Requests without Origin (e.g. no-JS form posts in some browsers) are allowed. */
function isOriginAllowed(origin, host, allowedOrigins) {
  if (!origin) return true;
  if (origin === 'null') return false;
  if (allowedOrigins.includes(origin)) return true;
  try { return host && new URL(origin).host === host; } catch { return false; }
}

module.exports = {
  SERVICES, BUDGETS, TIMELINES, CONTACT_PREFS, PLANS, LIMITS, MAX_BODY_BYTES, MIN_FILL_MS, makeReference, REFERENCE_RE,
  cleanText, validateSubmission, checkBotSignals, createRateLimiter, createDuplicateGuard,
  composeEmail, deliver, DeliveryError, getConfig, isOriginAllowed,
  classifyProviderError, sanitizeForLog, addressOf, idempotencyKey, DEFAULT_FROM, DEFAULT_TO,
};
